server:
  session-timeout: 1800
  tomcat:
    uri-encoding: UTF-8
  port: 9999
  servlet:
    context-path: /test # 项目名
    uri-encoding: utf-8

spring:
  application:
    name: test
  datasource: #数据库配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1 #redis 地址
    port: 6379
    database: 0
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 3
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  rabbitmq:
    ###开启消息确认机制 confirms
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        retry.enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
#  boot:
#    admin:
#      # 可视化管控台界面的 context-path
#      context-path: /monitor
#      client:
#        url: http://localhost:${server.port}/${server.servlet.context-path}/${spring.boot.admin.context-path}

param:
  elasticsearch:
    rest:
      ip-address: 127.0.0.1:8200
  uploadPath: D://loadFile/
  # 阿里巴巴支付
  alipay:
    # 二维码生成地址
    QRPath: D://ailpay.jpg
    appId: 2021001189664220
    url: https://openapi.alipay.com/gateway.do
    privateKey: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCR+cDKD7ZFjVUQblUTXz8WlLcj/sxyAlgPKBaZY+LbRmcPanizE8Bi9Z7B1fEi5o4jtCNju38YEhNFQchGO09TUa8L1v+lZx/nFyRg0k0566dUvMywh1sSAX5gbQhaDqTGRJKewUP9UMOyP+mXfqM9517UFtWCVZKPU//dYUjS/2HbcFqqzyyHzaQ5WibVYcd5P6GxHsGL62Jh3G+j/50U2mJZ6WqpK49LArg3/W4GcxahZEXoTsH4fPJJYZvrPHHoRFcfqHGbLZM1QNNoHreKiIXqVsycuv0E2gLfMHtBf4V4ms9cYSg2cjo53ZjR3pWgqKrv+LmNDRZlwY8VawEzAgMBAAECggEBAI0JmdOgyqL4oq91ao2FARd4KFqG3FFrIlnCidM6Rv1FUF38qRGci80RM4pkgs8No1ervGWnymwfSq8nl7EDrOj7iv0NhYLx2EkWevdxOVw06z9cCwikPsFu4AOaVO9uJpXJuz/XyzD8z5dxWOgeWup8mYqhZTjAJRKGPjhOvmXdECsaP15K4qJaRnLKIbGYlg9tlj3uoFxV+IE4OAgUA2Q61ClTMw8CMo+0lHm22C21CBglmv9JTtXttU4hsItUY/89j8V13O9C+PAPErXlOP5O6D25anXDjpQb09DJZ3xCC1MdOhag30yHE58M67z7eAnh3/ST9mg464g4z9GlOYECgYEA3iqMmM1m/CwlYCqNREQPStPGNMS1WLXRBVi3ATBqwAILtvKNXV45aeUJZBczfYhtGYLFx9MZ3jctopQPkVHNTunp3MEoGYrBVXZ758lxaV5lhEKjTjcv09NJCMkY/TVoKcpugIMgzkRXcuvVhvy4cnllcOVznjEEqa8CskQcojsCgYEAqDTPRhVifh+TRYZv6Uey55tWBMNAPjIHx1H7L4JxdzCipfQGUtKbMzONvJrfaG+9IJyr70xVym7hO5t7YccNEs6bn0LTIlIUr6Wz7cRK/DMGvnVmawawDCZ+vEJI0LogUapSa43g8ipbVfrwQOKK3hP6YaLPc+6NaBWG+Pqe9WkCgYEAlnEjshltgpf2W0+VR8P6wwXzMyp9TuwX9dHkYvbBYvI/sow/NBmpMU86c7/OS1SF5H+MpMsLulGNIom2nQZSy/xUM/vMxrcSQmgwcX4UwXB9t/lUEpQGXB+4Vi2vMU/oEFyXRYkGPwdCXHzcpEMgN8yC59dI2reA29K6NbMv3J8CgYB3IW/r4xlu2k4j36NDRVSgVJQHq4HEiwqXUKjmbSyPjhKkFsCjyCXDja/E9Ktl/D2m60+anCXmycEbxnMMPT41I790fI+srxWXkXRt4ah6FmmgWuW+x23ILTt1ejy4GBrrvAXDxyiaWwV1T9T5H3na76tVm0nygfIE1bpSfK44gQKBgBdW3slQVdF5oRACIQPAWHFxrMRwrcZdbmvvqYKVvv+sn98zWwpZgEMHnPYzSVz4H0vAkdKKhtlhOUCcgCuborpgeTa1fSqvuoaMaozf+cT/XcgSo1mv8UCTJXv1fzSxk21z+RFprIVe5ozDA7yOA/ZyMJir6C7fI+R65VIqhVlC"
    publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAh0UVrbad9DRdlNyHZxax3RXSS1KFPgjuunxTQwdeS1bn2VH7RhHMLN1oLRs74oB7QwC98p7gcJVTl4vppPyx/7Vd2Kkoy3u6Zv/BIRJZlBVI7CL+nWQme6yes2qcfWU+FOguAWcBNRNARNhfPIR35E7G9t7vcGG0/sMqjoaqGROBv9GoNg7PkAYIP3PU48dFTL1hZlJEq87LBLE94/oMMAmRk/kGn56qYDMqP9zQAOtbWvTvOvi50iu9/C5kVKtXGeZBcyJnWbSE5NtdB0c7PW5gZkLD3XwSqxqEGde4R/vKxCssRdw29X47u75JYNpTUHjrFEEEX88RrlQkyDZyjwIDAQAB"
  # 微信公众号
  weiXin:
    publicNumber:
      #  GET  获取access_token
      getTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential
      # get 获取用户openId
      getUserOpenIdUrl: https://api.weixin.qq.com/cgi-bin/user/get
      # POST/FORM 上传永久素材
      getUploadUrl: https://api.weixin.qq.com/cgi-bin/material/add_material
      # POST 上传永久图文素材
      getImgAndTextUrl: https://api.weixin.qq.com/cgi-bin/material/add_news?access_token={0}
      # POST/FORM 上传临时素材
      getInterimUploadUrl: https://api.weixin.qq.com/cgi-bin/media/upload
      # POST 上传临时图文素材
      getInterimImgAndTextUrl: https://api.weixin.qq.com/cgi-bin/media/uploadnews?access_token={0}
      # POST 根据标签进行群发
      getSendGroupMessageUrl: https://api.weixin.qq.com/cgi-bin/message/mass/sendall?access_token={0}
      #appId: wx719c0a02b4d27f68
      #appSecret: 290177152b14d76be33c9457559759ba
      # 测试数据
      appId: wxfcb53e10f150b957
      appSecret: a1e38469c1d3d3284e020ccb25e62014
  email:
    host: smtp.qq.com   # smtp.163.com
    from: 你的qq号@qq.com  # xxx@163.com
    username: 你的qq号 # xxx@163.com
    password: izrmuycyewejfgha # 163的邮箱授权码
